name: action file1
on: [push]
jobs:
  action-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps: 
      - uses: actions/checkout@v2
        with:
          githubactions: ${{ secrets.GITHUB_TOKEN }}
      - name: say something
        run: echo "i am working github action file"
      - name: Installing Tree
        run: sudo apt-get install tree
      - name: Showing Tree
        run: tree -L 4
      - name: npm install
        run: npm install
        env:
         NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Showing Tree
        run: tree -L 4
