name: Github-action

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
# a workflow contains more and more jobs
jobs:
  test-build:
    name: test-githubaction
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: use node js ${{matrix.node-version}}
        run: action file
      - uses: actions/checkout@master
        with:
          node-version: ${{matrix.node-version}}
        
      - name: check the code
        run: test action file
      - uses: actions/checkout@v2
      
      

      - name: run the code 
        run: test env
      - uses: actions/checkout@v2
        env: 
          username: SARASWATHI
          password: $DOCKERHUB_PASSWORD  
